apiVersion: v1
kind: Pod
metadata:
  name: irmgard-application
spec:
  containers:
    - image: zubeirtech/irmgard:0.4.2
      name: irmgard-application-container
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: irmgard-configmap
              key: POSTGRES_HOST
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: MINIO_SECRET_ACCESS_KEY
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: irmgard-configmap
              key: MINIO_ENDPOINT
      ports:
        - containerPort: 8080
          name: http