apiVersion: v1
kind: Pod
metadata:
  name: irmgard-application
spec:
  containers:
    - image: fischerjulian/irmgard:0.3.0
      name: irmgard-application-container
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: irmgard-configmap
              key: POSTGRES_HOST
      ports:
        - containerPort: 8080
          name: http