apiVersion: apps/v1
kind: Deployment
metadata:
  name: irmgard-depl
  labels:
    app: irmgard
  namespace: irmgard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irmgard
  template:
    metadata:
      labels:
        app: irmgard
    spec:
      containers:
      - name: irmgard
        image: fischerjulian/irmgard:0.3.0
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: irmgard-configmap
              key: POSTGRES_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: irmgard-svc
  namespace: irmgard
spec:
  selector:
    app: irmgard
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
