apiVersion: apps/v1
kind: Deployment
metadata:
  name: irmgard-depl
  labels:
    app: irmgard
  namespace: irmgard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irmgard
  template:
    metadata:
      labels:
        app: irmgard
    spec:
      containers:
      - name: irmgard-application-container
        image: zubeirtech/irmgard:0.4.4
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: irmgard-configmap
              key: POSTGRES_HOST
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: MINIO_SECRET_ACCESS_KEY
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: irmgard-configmap
              key: MINIO_ENDPOINT
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: RABBITMQ_PASS
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: irmgard-secret
              key: RABBITMQ_USER
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: irmgard-configmap
              key: RABBITMQ_HOST
        ports:
        - containerPort: 8080
          name: http