apiVersion: v1
kind: Secret
metadata:
  name: irmgard-secret
  namespace: irmgard
  labels:
    app: irmgard
type: Opaque
data:
  POSTGRES_USERNAME: "cG9zdGdyZXMK"
  POSTGRES_PASSWORD: "M25pcmZpNGJ2ZnYK"
