apiVersion: v1
kind: Pod
metadata:
  name: postgresql-application
spec:
  containers:
    - image: fischerjulian/smpl-go-pg:0.2.0
      name: postgresql-application-container
      env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgresql-secret-2
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret-2
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgresql-secret-2
              key: POSTGRES_HOST
      ports:
        - containerPort: 8080
          name: http
  restartPolicy: Always