apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-depl
  labels:
    app: yolo
  namespace: yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: yolo
        image: zubeirtech/facerecognition-yolo:0.3.0
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: yolo-configmap
              key: RABBITMQ_HOST
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: yolo-secret
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: yolo-secret
              key: RABBITMQ_PASS
        - name: OBJECT_STORE_HOST
          valueFrom:
            configMapKeyRef:
              name: yolo-configmap
              key: OBJECT_STORE_HOST
        - name: OBJECT_STORE_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: yolo-secret
              key: OBJECT_STORE_ACCESS_KEY_ID
        - name: OBJECT_STORE_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: yolo-secret
              key: OBJECT_STORE_SECRET_ACCESS_KEY
