apiVersion: v1
data:
  default_user.conf: ZGVmYXVsdF91c2VyID0gZGVmYXVsdF91c2VyX0Z3WHlLUlZIODRfNXg3WVlRb3EKZGVmYXVsdF9wYXNzID0gd19aVEpGRFJ3aUdudlpURHBpZHVNaEh0REdteFZhb0UK
  host: cmFiYml0bXEtY2x1c3Rlci5yYWJiaXRtcS1zeXN0ZW0uc3Zj
  password: d19aVEpGRFJ3aUdudlpURHBpZHVNaEh0REdteFZhb0U=
  port: NTY3Mg==
  provider: cmFiYml0bXE=
  type: cmFiYml0bXE=
  username: ZGVmYXVsdF91c2VyX0Z3WHlLUlZIODRfNXg3WVlRb3E=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-cluster-default-user
  namespace: rabbitmq-system
  ownerReferences:
  - apiVersion: rabbitmq.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: RabbitmqCluster
    name: rabbitmq-cluster
    uid: 880aa29b-ac14-4ba4-9fe3-45f792b8187c
  resourceVersion: "337645"
  uid: 30982f4e-5f38-4595-90f6-1f89a5a5d82e
type: Opaque
