apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
data:
  root-user: QUtJQUlPU0ZPRE5ON0VYQU1QTEUK
  root-password: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQo=
  